# Generated by Django 4.2.2 on 2023-06-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tinder", "0003_chat_message_messageimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="adress",
            field=models.CharField(default="Алалыкина 12"),
        ),
        migrations.AddField(
            model_name="order",
            name="adress_link",
            field=models.URLField(
                blank=True,
                default="https://2gis.kz/karaganda/geo/70000001039962960",
                null=True,
            ),
        ),
    ]
