# Generated by Django 4.2.2 on 2023-06-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tinder", "0004_order_adress_order_adress_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="adress",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="adress_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
